customer_manager_home:
    path: /
    defaults: { _controller:AppBundle:Home:index}

customer_manager_customers_index:
    path: /customers
    defaults: { _controller:AppBundle:Customers:index}

customer_manager_customers_register:
    path: /customers/register
    defaults: { _controller:AppBundle:Customers:register}

customer_manager_customers_add:
    path: /customers/add
    defaults: { _controller:AppBundle:Customers:add}

customer_manager_customers_update:
    path: /customers/update/{id}
    defaults: { _controller:AppBundle:Customers:update}

customer_manager_customers_edit:
    path: /customers/edit/{id}
    defaults: { _controller:AppBundle:Customers:edit}

customer_manager_customers_delete:
    path: /customers/delete/{id}
    defaults: { _controller:AppBundle:Customers:delete}

customer_manager_appointment_index:
    path: /appointments
    defaults: { _controller:AppBundle:Appointments:index}

customer_manager_appointment_register:
    path: /appointments/register
    defaults: { _controller:AppBundle:Appointments:register}

customer_manager_appointment_add:
    path: /appointments/add
    defaults: { _controller:AppBundle:Appointments:add}

customer_manager_appointment_update:
    path: /appointments/update/{id}
    defaults: { _controller:AppBundle:Appointments:update}

customer_manager_appointment_edit:
    path: /appointments/edit/{id}
    defaults: { _controller:AppBundle:Appointments:edit}

customer_manager_appointment_delete:
    path: /appointments/delete/{id}
    defaults: { _controller:AppBundle:Appointments:delete}

customer_manager_demand_index:
    path: /demands
    defaults: { _controller:AppBundle:Demand:index}

customer_manager_demand_register:
    path: /demands/register
    defaults: { _controller:AppBundle:Demand:register}

customer_manager_demand_add:
      path: /demands/add
      defaults: { _controller:AppBundle:Demand:add}

customer_manager_demand_delete:
    path: /demands/delete/{id}
    defaults: { _controller:AppBundle:Demand:delete}

customer_manager_demand_edit:
    path: /demands/edit/{id}
    defaults: { _controller:AppBundle:Demand:edit}

customer_manager_demand_update:
    path: /demands/update/{id}
    defaults: { _controller:AppBundle:Demand:update}

customer_manager_services_index:
    path: /services
    defaults: { _controller:AppBundle:Services:index}

customer_manager_services_birthday_message:
    path: /services/birthday
    defaults: { _controller:AppBundle:Services:birthdayMessage}

customer_manager_services_birthday_today_notify:
    path: /services/birthday/notify/today
    defaults: { _controller:AppBundle:Services:birthdayNotify}

customer_manager_services_custom_message:
    path: /services/custom
    defaults: { _controller:AppBundle:Services:customMessage}

customer_manager_services_appointment_reminder:
    path: /services/appointment-reminder
    defaults: { _controller:AppBundle:Services:appointmentReminder}

customer_manager_services_appointment_notify:
    path: /services/appointment-reminder/notify/{by}
    defaults: { _controller:AppBundle:Services:appointmentNotify}

customer_manager_send_message:
    path: /message/send
    defaults: { _controller:AppBundle:Mailer:send}

customer_manager_index:
    path: /index
    defaults: { _controller:AppBundle:Navigation:index}

customer_manager_register:
    path: /register
    defaults: { _controller:AppBundle:Navigation:register}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


