# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     appointment_manager:
             class:        AppBundle\DependencyInjection\AppointmentManager
             arguments:    ["@doctrine.orm.entity_manager"]
     customer_manager:
                  class:        AppBundle\DependencyInjection\CustomerManager
                  arguments:    ["@doctrine.orm.entity_manager"]
     demand_manager:
                       class:        AppBundle\DependencyInjection\DemandManager
                       arguments:    ["@doctrine.orm.entity_manager"]
     helper_validator:
                       class:        AppBundle\DependencyInjection\HelperValidator
     remove_listener:
             class: AppBundle\EventListener\RemoveListener
             tags:
                 - { name: doctrine.event_listener, event: preRemove }
